' Developer Express Code Central Example:
' How to load data from a SQL Geometry data source
' 
' This example demonstrates how to load data to a vector layer from a SQL Geometry
' data source.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=T175898
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace SqlGeometry.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As SqlGeometry.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New SqlGeometry.Properties.Settings())), SqlGeometry.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return SqlGeometry.Properties.Settings.defaultInstance
            End Get
        End Property
    End Class
End Namespace
